name: Project check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  check:
    name: Check

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: cache-npm-${{ hashFiles('./package-lock.json') }}
          restore-keys: cache-npm-

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: npm run lint
        env:
          FORCE_COLOR: true
