name: Deploy on pull request

on:
  pull_request_target:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  deploy-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'refs/pull/${{ github.event.pull_request.number }}/merge'
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./build
          branch: gh-pages
          target-folder: ${{ github.event.pull_request.number }}
